INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_MANCHESTER_DECODE manchester_decode)

FIND_PATH(
    MANCHESTER_DECODE_INCLUDE_DIRS
    NAMES manchester_decode/api.h
    HINTS $ENV{MANCHESTER_DECODE_DIR}/include
        ${PC_MANCHESTER_DECODE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    MANCHESTER_DECODE_LIBRARIES
    NAMES gnuradio-manchester_decode
    HINTS $ENV{MANCHESTER_DECODE_DIR}/lib
        ${PC_MANCHESTER_DECODE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/manchester_decodeTarget.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MANCHESTER_DECODE DEFAULT_MSG MANCHESTER_DECODE_LIBRARIES MANCHESTER_DECODE_INCLUDE_DIRS)
MARK_AS_ADVANCED(MANCHESTER_DECODE_LIBRARIES MANCHESTER_DECODE_INCLUDE_DIRS)
