/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(synced_manchester_decode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a1c5bea7ac2ed805232e6efcf6baa738)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/synced_manchester_decode/synced_manchester_decode.h>
// pydoc.h is automatically generated in the build directory
#include <synced_manchester_decode_pydoc.h>

template <typename T>
void bind_synced_manchester_decode_template(py::module& m, const char* classname)
{
    using synced_manchester_decode = gr::synced_manchester_decode::synced_manchester_decode<T>;

    py::class_<synced_manchester_decode, 
                gr::block, 
                gr::basic_block,
                std::shared_ptr<synced_manchester_decode>>(m, classname, D(synced_manchester_decode))
        .def(py::init(&synced_manchester_decode::make), D(synced_manchester_decode, make));
}

void bind_synced_manchester_decode(py::module& m)
{
    bind_synced_manchester_decode_template<std::uint8_t>(m, "synced_manchester_decode_b");
    bind_synced_manchester_decode_template<std::int16_t>(m, "synced_manchester_decode_s");
    bind_synced_manchester_decode_template<std::int32_t>(m, "synced_manchester_decode_i");
    bind_synced_manchester_decode_template<float>(m, "synced_manchester_decode_f");
}
