/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-synced_manchester_decode
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_SYNCED_MANCHESTER_DECODE_API_H
#define INCLUDED_SYNCED_MANCHESTER_DECODE_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_synced_manchester_decode_EXPORTS
#define SYNCED_MANCHESTER_DECODE_API __GR_ATTR_EXPORT
#else
#define SYNCED_MANCHESTER_DECODE_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_SYNCED_MANCHESTER_DECODE_API_H */
