/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(manchester_decode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1b3d634e1f9558eaea9da5e3e1a93430)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/manchester_decode/manchester_decode.h>
// pydoc.h is automatically generated in the build directory
#include <manchester_decode_pydoc.h>

template <typename T>
void bind_manchester_decode_template(py::module& m, const char* classname)
{
    using manchester_decode = gr::manchester_decode::manchester_decode<T>;

    py::class_<manchester_decode, 
                gr::block, 
                gr::basic_block,
                std::shared_ptr<manchester_decode>>(m, classname, D(manchester_decode))
        .def(py::init(&manchester_decode::make), D(manchester_decode, make));
}

void bind_manchester_decode(py::module& m)
{
    bind_manchester_decode_template<std::int16_t>(m, "manchester_decode_s");
    bind_manchester_decode_template<std::int32_t>(m, "manchester_decode_i");
    bind_manchester_decode_template<float>(m, "manchester_decode_f");
}





