INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_MANCHESTER_ENCODE manchester_encode)

FIND_PATH(
    MANCHESTER_ENCODE_INCLUDE_DIRS
    NAMES manchester_encode/api.h
    HINTS $ENV{MANCHESTER_ENCODE_DIR}/include
        ${PC_MANCHESTER_ENCODE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    MANCHESTER_ENCODE_LIBRARIES
    NAMES gnuradio-manchester_encode
    HINTS $ENV{MANCHESTER_ENCODE_DIR}/lib
        ${PC_MANCHESTER_ENCODE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/manchester_encodeTarget.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MANCHESTER_ENCODE DEFAULT_MSG MANCHESTER_ENCODE_LIBRARIES MANCHESTER_ENCODE_INCLUDE_DIRS)
MARK_AS_ADVANCED(MANCHESTER_ENCODE_LIBRARIES MANCHESTER_ENCODE_INCLUDE_DIRS)
